export const GET_ALL_PAYMENT_SUCCESS = 'GET_ALL_PAYMENT_SUCCESS'
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS'
export const EDIT_PAYMENT_SUCCESS = 'EDIT_PAYMENT_SUCCESS'
export const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS'