export const GET_ALL_PERMISSION_SUCCESS = 'GET_ALL_PERMISSION_SUCCESS'
export const CREATE_PERMISSION_SUCCESS = 'CREATE_PERMISSION_SUCCESS'
export const EDIT_PERMISSION_SUCCESS = 'EDIT_PERMISSION_SUCCESS'
export const DELETE_PERMISSION_SUCCESS = 'DELETE_PERMISSION_SUCCESS'