/////////Rank/////////
export const GET_ALL_RANK_SUCCESS = "GET_ALL_RANK_SUCCESS";
export const CREATE_RANK_SUCCESS = "CREATE_RANK_SUCCESS";
export const EDIT_RANK_SUCCESS = "EDIT_RANK_SUCCESS";
export const DELETE_RANK_SUCCESS = "DELETE_RANK_SUCCESS";
export const GET_RANK_BY_ID_SUCCESS = "GET_RANK_BY_ID_SUCCESS";
/////////Position/////////

export const GET_ALL_POSITION_SUCCESS = "GET_ALL_POSITION_SUCCESS";
export const CREATE_POSITION_SUCCESS = "CREATE_POSITION_SUCCESS";
export const EDIT_POSITION_SUCCESS = "EDIT_POSITION_SUCCESS";
export const DELETE_POSITION_SUCCESS = "DELETE_POSITION_SUCCESS";
