export const GET_REPORT_BY_RESEARCH_SUCCESS = "GET_REPORT_BY_RESEARCH_SUCCESS";
export const GET_REPORT_BY_SUBJECT_SUCCESS = "GET_REPORT_BY_SUBJECT_SUCCESS";
export const GET_REPORT_BY_USER_SUCCESS = "GET_REPORT_BY_USER_SUCCESS";
export const GET_REPORT_BY_DEPARTMENT_SUCCESS =
  "GET_REPORT_BY_DEPARTMENT_SUCCESS";
export const GET_REPORT_BY_ACCOUNTING_SUCCESS =
  "GET_REPORT_BY_ACCOUNTING_SUCCESS";
export const GET_REPORT_BY_LECTURER_SUCCESS = "GET_REPORT_BY_LECTURER_SUCCESS";
