export const GET_ALL_RESEARCH_SUCCESS = "GET_ALL_RESEARCH_SUCCESS";
export const GET_RESEARCH_BY_USER_ID_SUCCESS =
  "GET_RESEARCH_BY_USER_ID_SUCCESS";
export const GET_RESEARCH_BY_ID_SUCCESS = "GET_RESEARCH_BY_ID_SUCCESS";
export const CREATE_RESEARCH_SUCCESS = "CREATE_RESEARCH_SUCCESS";
export const EDIT_RESEARCH_SUCCESS = "EDIT_RESEARCH_SUCCESS";
export const DELETE_RESEARCH_SUCCESS = "DELETE_RESEARCH_SUCCESS";
export const ACTION_RESEARCH_SUCCESS = "ACTION_RESEARCH_SUCCESS";
