export const GET_ALL_SEMESTER_SUCCESS = "GET_ALL_SEMESTER_SUCCESS";
export const CREATE_SEMESTER_SUCCESS = "CREATE_SEMESTER_SUCCESS";
export const EDIT_SEMESTER_SUCCESS = "EDIT_SEMESTER_SUCCESS";
export const DELETE_SEMESTER_SUCCESS = "DELETE_SEMESTER_SUCCESS";
