export const GET_ALL_SUBJECT_SUCCESS = "GET_ALL_SUBJECT_SUCCESS";
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS";
export const EDIT_SUBJECT_SUCCESS = "EDIT_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const GET_SUBJECT_BY_ID_SUCCESS = "GET_SUBJECT_BY_ID_SUCCESS";
export const GET_SUBJECT_BY_DEPARTMENT_SUCCESS =
  "GET_SUBJECT_BY_DEPARTMENT_SUCCESS";
